# Generated by Django 2.2 on 2020-03-04 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hitcounter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
