# Generated by Django 2.2.10 on 2021-02-21 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epoch',
            name='date',
            field=models.DateField(default=datetime.date(2021, 2, 21)),
            preserve_default=False,
        ),
    ]
