# Generated by Django 2.2.10 on 2021-02-19 20:44

from django.db import migrations


def migrate_data(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Epoch = apps.get_model('hitl', 'Epoch')
    
    epochs = [
        ["2015-07-01", "July 2015", "HITL_System_v0/AD_model/combined_output/07_2015/AD_output.csv"],
        ["2015-08-01", "August 2015", "HITL_System_v0/AD_model/combined_output/08_2015/AD_output.csv"],
        ["2015-09-01", "September 2015", "HITL_System_v0/AD_model/combined_output/09_2015/AD_output.csv"],
        ["2015-10-01", "October 2015", "HITL_System_v0/AD_model/combined_output/10_2015/AD_output.csv"],
        ["2015-11-01", "November 2015", "HITL_System_v0/AD_model/combined_output/11_2015/AD_output.csv"],
        ["2015-12-01", "December 2015", "HITL_System_v0/AD_model/combined_output/12_2015/AD_output.csv"],
        ["2016-01-01", "January 2016", "HITL_System_v0/AD_model/combined_output/01_2016/AD_output.csv"],
        ["2016-02-01", "February 2016", "HITL_System_v0/AD_model/combined_output/02_2016/AD_output.csv"],
        ["2016-03-01", "March 2016", "HITL_System_v0/AD_model/combined_output/03_2016/AD_output.csv"],
        ["2016-04-01", "April 2016", "HITL_System_v0/AD_model/combined_output/04_2016/AD_output.csv"],
        ["2016-05-01", "May 2016", "HITL_System_v0/AD_model/combined_output/05_2016/AD_output.csv"],
        ["2016-06-01", "June 2016", "HITL_System_v0/AD_model/combined_output/06_2016/AD_output.csv"],
        ["2016-07-01", "July 2016", "HITL_System_v0/AD_model/combined_output/07_2016/AD_output.csv"],
        ["2016-08-01", "August 2016", "HITL_System_v0/AD_model/combined_output/08_2016/AD_output.csv"],
        ["2016-09-01", "September 2016", "HITL_System_v0/AD_model/combined_output/09_2016/AD_output.csv"],
        ["2016-10-01", "October 2016", "HITL_System_v0/AD_model/combined_output/10_2016/AD_output.csv"],
        ["2016-11-01", "November 2016", "HITL_System_v0/AD_model/combined_output/11_2016/AD_output.csv"],
        ["2016-12-01", "December 2016", "HITL_System_v0/AD_model/combined_output/12_2016/AD_output.csv"],
        ["2017-01-01", "January 2017", "HITL_System_v0/AD_model/combined_output/01_2017/AD_output.csv"],
        ["2017-02-01", "February 2017", "HITL_System_v0/AD_model/combined_output/02_2017/AD_output.csv"],
        ["2017-03-01", "March 2017", "HITL_System_v0/AD_model/combined_output/03_2017/AD_output.csv"],
        ["2017-04-01", "April 2017", "HITL_System_v0/AD_model/combined_output/04_2017/AD_output.csv"],
        ["2017-05-01", "May 2017", "HITL_System_v0/AD_model/combined_output/05_2017/AD_output.csv"],
        ["2017-06-01", "June 2017", "HITL_System_v0/AD_model/combined_output/06_2017/AD_output.csv"],
        ["2017-07-01", "July 2017", "HITL_System_v0/AD_model/combined_output/07_2017/AD_output.csv"],
        ["2017-08-01", "August 2017", "HITL_System_v0/AD_model/combined_output/08_2017/AD_output.csv"],
        ["2017-09-01", "September 2017", "HITL_System_v0/AD_model/combined_output/09_2017/AD_output.csv"],
        ["2017-10-01", "October 2017", "HITL_System_v0/AD_model/combined_output/10_2017/AD_output.csv"],
        ["2017-11-01", "November 2017", "HITL_System_v0/AD_model/combined_output/11_2017/AD_output.csv"],
        ["2017-12-01", "December 2017", "HITL_System_v0/AD_model/combined_output/12_2017/AD_output.csv"],
    ]

    for date, name, path in epochs:
        Epoch.objects.create(date=date, name=name, path=path)


class Migration(migrations.Migration):

    dependencies = [
        ('hitl', '0002_epoch_date'),
    ]

    operations = [
        migrations.RunPython(migrate_data, migrations.RunPython.noop),
    ]
