# Generated by Django 2.2 on 2019-05-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChinaExport',
            fields=[
                ('panjivarecordid', models.BigIntegerField(db_column='PanjivaRecordID', primary_key=True, serialize=False)),
                ('shipmentmonth', models.DateField(blank=True, db_column='ShipmentMonth', null=True)),
                ('shippername', models.TextField(blank=True, db_column='ShipperName', null=True)),
                ('shipperpanjivaid', models.BigIntegerField(blank=True, db_column='ShipperPanjivaID', null=True)),
                ('shipperultimateparentname', models.TextField(blank=True, db_column='ShipperUltimateParentName', null=True)),
                ('shipmentdestination', models.CharField(blank=True, db_column='ShipmentDestination', max_length=255, null=True)),
                ('countryofsale', models.CharField(blank=True, db_column='CountryOfSale', max_length=255, null=True)),
                ('transportmethod', models.TextField(blank=True, db_column='TransportMethod', null=True)),
                ('iscontainerized', models.CharField(blank=True, db_column='IsContainerized', max_length=255, null=True)),
                ('valueofgoodsusd', models.BigIntegerField(blank=True, db_column='ValueOfGoodsUSD', null=True)),
                ('hscode', models.IntegerField(blank=True, db_column='HSCode', null=True)),
                ('hscodekeywords', models.TextField(blank=True, db_column='HSCodeKeywords', null=True)),
                ('adminregion', models.CharField(blank=True, db_column='AdminRegion', max_length=255, null=True)),
                ('tradetype', models.TextField(blank=True, db_column='TradeType', null=True)),
            ],
            options={
                'db_table': 'china_export',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChinaImport',
            fields=[
                ('panjivarecordid', models.BigIntegerField(db_column='PanjivaRecordID', primary_key=True, serialize=False)),
                ('shipmentmonth', models.DateField(blank=True, db_column='ShipmentMonth', null=True)),
                ('consigneename', models.TextField(blank=True, db_column='ConsigneeName', null=True)),
                ('consigneecity', models.CharField(blank=True, db_column='ConsigneeCity', max_length=255, null=True)),
                ('consigneecountry', models.CharField(blank=True, db_column='ConsigneeCountry', max_length=255, null=True)),
                ('consigneepanjivaid', models.BigIntegerField(blank=True, db_column='ConsigneePanjivaID', null=True)),
                ('shipmentorigin', models.CharField(blank=True, db_column='ShipmentOrigin', max_length=255, null=True)),
                ('province', models.CharField(blank=True, db_column='Province', max_length=255, null=True)),
                ('countryofsale', models.CharField(blank=True, db_column='CountryOfSale', max_length=255, null=True)),
                ('transportmethod', models.TextField(blank=True, db_column='TransportMethod', null=True)),
                ('iscontainerized', models.CharField(blank=True, db_column='IsContainerized', max_length=255, null=True)),
                ('valueofgoodsusd', models.BigIntegerField(blank=True, db_column='ValueOfGoodsUSD', null=True)),
                ('hscode', models.IntegerField(blank=True, db_column='HSCode', null=True)),
                ('hscodekeywords', models.TextField(blank=True, db_column='HSCodeKeywords', null=True)),
                ('adminregion', models.CharField(blank=True, db_column='AdminRegion', max_length=255, null=True)),
                ('tradetype', models.TextField(blank=True, db_column='TradeType', null=True)),
            ],
            options={
                'db_table': 'china_import',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeruExport',
            fields=[
                ('panjivarecordid', models.BigIntegerField(db_column='PanjivaRecordID', primary_key=True, serialize=False)),
                ('shippername', models.TextField(blank=True, db_column='ShipperName', null=True)),
                ('shippercity', models.CharField(blank=True, db_column='ShipperCity', max_length=255, null=True)),
                ('shipperstateregion', models.CharField(blank=True, db_column='ShipperStateRegion', max_length=255, null=True)),
                ('shippercountry', models.CharField(blank=True, db_column='ShipperCountry', max_length=255, null=True)),
                ('shipperultimateparentname', models.TextField(blank=True, db_column='ShipperUltimateParentName', null=True)),
                ('shipmentdestination', models.CharField(blank=True, db_column='ShipmentDestination', max_length=255, null=True)),
                ('portofunlading', models.TextField(blank=True, db_column='PortOfUnlading', null=True)),
                ('portofunladingcountry', models.CharField(blank=True, db_column='PortOfUnladingCountry', max_length=255, null=True)),
                ('transportmethod', models.TextField(blank=True, db_column='TransportMethod', null=True)),
                ('hscode', models.IntegerField(blank=True, db_column='HSCode', null=True)),
                ('goodsshipped', models.TextField(blank=True, db_column='GoodsShipped', null=True)),
                ('iscontainerized', models.CharField(blank=True, db_column='IsContainerized', max_length=255, null=True)),
                ('volumeteu', models.FloatField(blank=True, db_column='VolumeTEU', null=True)),
                ('itemquantity', models.FloatField(blank=True, db_column='ItemQuantity', null=True)),
                ('grossweightkg', models.FloatField(blank=True, db_column='GrossWeightKg', null=True)),
                ('netweightkg', models.FloatField(blank=True, db_column='NetWeightKg', null=True)),
                ('valueofgoodsfobusd', models.FloatField(blank=True, db_column='ValueOfGoodsFOBUSD', null=True)),
                ('exportquantity', models.FloatField(blank=True, db_column='ExportQuantity', null=True)),
                ('exportunit', models.CharField(blank=True, db_column='ExportUnit', max_length=255, null=True)),
                ('receiptdeclarationdate', models.DateField(blank=True, db_column='ReceiptDeclarationDate', null=True)),
            ],
            options={
                'db_table': 'peru_export',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsImport',
            fields=[
                ('panjivarecordid', models.BigIntegerField(db_column='PanjivaRecordID', primary_key=True, serialize=False)),
                ('arrivaldate', models.DateField(blank=True, db_column='ArrivalDate', null=True)),
                ('consigneename', models.TextField(blank=True, db_column='ConsigneeName', null=True)),
                ('consigneecity', models.CharField(blank=True, db_column='ConsigneeCity', max_length=255, null=True)),
                ('consigneecountry', models.CharField(blank=True, db_column='ConsigneeCountry', max_length=255, null=True)),
                ('consigneepanjivaid', models.BigIntegerField(blank=True, db_column='ConsigneePanjivaID', null=True)),
                ('consigneeultimateparentname', models.TextField(blank=True, db_column='ConsigneeUltimateParentName', null=True)),
                ('shipperpanjivaid', models.CharField(blank=True, db_column='ShipperPanjivaID', max_length=255, null=True)),
                ('carrier', models.CharField(blank=True, db_column='Carrier', max_length=255, null=True)),
                ('shipmentorigin', models.CharField(blank=True, db_column='ShipmentOrigin', max_length=255, null=True)),
                ('shipmentdestination', models.CharField(blank=True, db_column='ShipmentDestination', max_length=255, null=True)),
                ('portofunlading', models.CharField(blank=True, db_column='PortOfUnlading', max_length=255, null=True)),
                ('portoflading', models.CharField(blank=True, db_column='PortOfLading', max_length=255, null=True)),
                ('placeofreceipt', models.CharField(blank=True, db_column='PlaceOfReceipt', max_length=255, null=True)),
                ('volumeteu', models.FloatField(blank=True, db_column='VolumeTEU', null=True)),
                ('weightkg', models.FloatField(blank=True, db_column='WeightKg', null=True)),
                ('haslcl', models.CharField(blank=True, db_column='HasLCL', max_length=255, null=True)),
                ('containernumbers', models.TextField(blank=True, db_column='ContainerNumbers', null=True)),
                ('hscode', models.IntegerField(blank=True, db_column='HSCode', null=True)),
                ('goodsshipped', models.TextField(blank=True, db_column='GoodsShipped', null=True)),
                ('dividedlcl', models.CharField(blank=True, db_column='DividedLCL', max_length=255, null=True)),
            ],
            options={
                'db_table': 'us_import',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChinaExportComment',
            fields=[
                ('panjivarecordid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChinaImportComment',
            fields=[
                ('panjivarecordid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PeruExportComment',
            fields=[
                ('panjivarecordid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UsImportComment',
            fields=[
                ('panjivarecordid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
            ],
        ),
    ]
