# Generated by Django 2.2 on 2019-10-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_chinaexportthumbs_chinaimportthumbs_peruexportthumbs_usimportthumbs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flags',
            fields=[
                ('panjivarecordid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('leb', models.BooleanField(default=False)),
                ('cites', models.BooleanField(default=False)),
                ('high', models.BooleanField(default=False)),
                ('iucn', models.BooleanField(default=False)),
                ('lacey', models.BooleanField(default=False)),
                ('text', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Flags',
                'verbose_name_plural': 'Flags',
            },
        ),
    ]
