# Generated by Django 2.2 on 2019-10-30 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0003_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='chinaexportcomment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chinaexportthumbs',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chinaimportcomment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chinaimportthumbs',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peruexportcomment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peruexportthumbs',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usimportcomment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usimportthumbs',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='chinaexportcomment',
            unique_together={('user', 'panjivarecordid')},
        ),
        migrations.AlterUniqueTogether(
            name='chinaexportthumbs',
            unique_together={('user', 'panjivarecordid')},
        ),
        migrations.AlterUniqueTogether(
            name='chinaimportcomment',
            unique_together={('user', 'panjivarecordid')},
        ),
        migrations.AlterUniqueTogether(
            name='chinaimportthumbs',
            unique_together={('user', 'panjivarecordid')},
        ),
        migrations.AlterUniqueTogether(
            name='peruexportcomment',
            unique_together={('user', 'panjivarecordid')},
        ),
        migrations.AlterUniqueTogether(
            name='peruexportthumbs',
            unique_together={('user', 'panjivarecordid')},
        ),
        migrations.AlterUniqueTogether(
            name='usimportcomment',
            unique_together={('user', 'panjivarecordid')},
        ),
        migrations.AlterUniqueTogether(
            name='usimportthumbs',
            unique_together={('user', 'panjivarecordid')},
        ),
    ]
