# Generated by Django 2.2 on 2019-10-31 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsImportThumbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panjivarecordid', models.BigIntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('thumbs', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('clear', 'Clear')], default='clear', max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'panjivarecordid')},
            },
        ),
        migrations.CreateModel(
            name='UsImportComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panjivarecordid', models.BigIntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'panjivarecordid')},
            },
        ),
        migrations.CreateModel(
            name='PeruExportThumbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panjivarecordid', models.BigIntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('thumbs', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('clear', 'Clear')], default='clear', max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'panjivarecordid')},
            },
        ),
        migrations.CreateModel(
            name='PeruExportComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panjivarecordid', models.BigIntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'panjivarecordid')},
            },
        ),
        migrations.CreateModel(
            name='ChinaImportThumbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panjivarecordid', models.BigIntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('thumbs', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('clear', 'Clear')], default='clear', max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'panjivarecordid')},
            },
        ),
        migrations.CreateModel(
            name='ChinaImportComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panjivarecordid', models.BigIntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'panjivarecordid')},
            },
        ),
        migrations.CreateModel(
            name='ChinaExportThumbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panjivarecordid', models.BigIntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('thumbs', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('clear', 'Clear')], default='clear', max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'panjivarecordid')},
            },
        ),
        migrations.CreateModel(
            name='ChinaExportComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panjivarecordid', models.BigIntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'panjivarecordid')},
            },
        ),
    ]
